# CMake generated Testfile for 
# Source directory: C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import
# Build directory: C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/cm_mods/builds/json/tests/cmake_import
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cmake_import_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 17 2022" "-A" "" "-DCMAKE_CXX_COMPILER=D:/VSCODE 2022/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_DIR=C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/cm_mods/builds/json" "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/project")
  set_tests_properties(cmake_import_configure PROPERTIES  FIXTURES_SETUP "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;1;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cmake_import_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 17 2022" "-A" "" "-DCMAKE_CXX_COMPILER=D:/VSCODE 2022/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_DIR=C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/cm_mods/builds/json" "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/project")
  set_tests_properties(cmake_import_configure PROPERTIES  FIXTURES_SETUP "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;1;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cmake_import_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 17 2022" "-A" "" "-DCMAKE_CXX_COMPILER=D:/VSCODE 2022/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_DIR=C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/cm_mods/builds/json" "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/project")
  set_tests_properties(cmake_import_configure PROPERTIES  FIXTURES_SETUP "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;1;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cmake_import_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 17 2022" "-A" "" "-DCMAKE_CXX_COMPILER=D:/VSCODE 2022/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_DIR=C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/cm_mods/builds/json" "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/project")
  set_tests_properties(cmake_import_configure PROPERTIES  FIXTURES_SETUP "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;1;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;0;")
else()
  add_test(cmake_import_configure NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cmake_import_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_import_build PROPERTIES  FIXTURES_REQUIRED "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;9;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cmake_import_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_import_build PROPERTIES  FIXTURES_REQUIRED "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;9;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cmake_import_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_import_build PROPERTIES  FIXTURES_REQUIRED "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;9;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cmake_import_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_import_build PROPERTIES  FIXTURES_REQUIRED "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;9;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_import/CMakeLists.txt;0;")
else()
  add_test(cmake_import_build NOT_AVAILABLE)
endif()
