# CMake generated Testfile for 
# Source directory: C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content
# Build directory: C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/cm_mods/builds/json/tests/cmake_fetch_content
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cmake_fetch_content_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 17 2022" "-DCMAKE_CXX_COMPILER=D:/VSCODE 2022/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_source=C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json" "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/project")
  set_tests_properties(cmake_fetch_content_configure PROPERTIES  FIXTURES_SETUP "cmake_fetch_content" LABELS "git_required;not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;2;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cmake_fetch_content_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 17 2022" "-DCMAKE_CXX_COMPILER=D:/VSCODE 2022/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_source=C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json" "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/project")
  set_tests_properties(cmake_fetch_content_configure PROPERTIES  FIXTURES_SETUP "cmake_fetch_content" LABELS "git_required;not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;2;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cmake_fetch_content_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 17 2022" "-DCMAKE_CXX_COMPILER=D:/VSCODE 2022/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_source=C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json" "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/project")
  set_tests_properties(cmake_fetch_content_configure PROPERTIES  FIXTURES_SETUP "cmake_fetch_content" LABELS "git_required;not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;2;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cmake_fetch_content_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 17 2022" "-DCMAKE_CXX_COMPILER=D:/VSCODE 2022/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_source=C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json" "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/project")
  set_tests_properties(cmake_fetch_content_configure PROPERTIES  FIXTURES_SETUP "cmake_fetch_content" LABELS "git_required;not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;2;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;0;")
else()
  add_test(cmake_fetch_content_configure NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cmake_fetch_content_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_fetch_content_build PROPERTIES  FIXTURES_REQUIRED "cmake_fetch_content" LABELS "git_required;not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;9;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cmake_fetch_content_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_fetch_content_build PROPERTIES  FIXTURES_REQUIRED "cmake_fetch_content" LABELS "git_required;not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;9;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cmake_fetch_content_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_fetch_content_build PROPERTIES  FIXTURES_REQUIRED "cmake_fetch_content" LABELS "git_required;not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;9;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cmake_fetch_content_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_fetch_content_build PROPERTIES  FIXTURES_REQUIRED "cmake_fetch_content" LABELS "git_required;not_reproducible" _BACKTRACE_TRIPLES "C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;9;add_test;C:/Users/wbhag/Desktop/CS/Personal Programming Ventures/RiscV_Assembler_2/third-party/json/tests/cmake_fetch_content/CMakeLists.txt;0;")
else()
  add_test(cmake_fetch_content_build NOT_AVAILABLE)
endif()
